# Generated by Django 3.1.4 on 2020-12-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talantuser',
            name='access_token',
            field=models.CharField(max_length=2500),
        ),
    ]
