# Generated by Django 3.1.4 on 2020-12-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201210_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='talantuser',
            name='cs_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talantuser',
            name='cs_result',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='talantuser',
            name='dota_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talantuser',
            name='dota_result',
            field=models.FloatField(default=None, null=True),
        ),
    ]
