# Generated by Django 3.1.4 on 2020-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201214_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='talantuser',
            name='cs_task',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talantuser',
            name='dota_task',
            field=models.CharField(default='', max_length=100),
        ),
    ]
