# Generated by Django 3.1.4 on 2021-01-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210111_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(default=None, max_length=200, null=True)),
                ('result', models.CharField(default=None, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DotaResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(default=None, max_length=200, null=True)),
                ('result', models.CharField(default=None, max_length=2500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='talantuser',
            name='cs_result',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.csresult'),
        ),
        migrations.AlterField(
            model_name='talantuser',
            name='dota_result',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dotaresult'),
        ),
    ]
