# Generated by Django 3.1.4 on 2021-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210114_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talantuser',
            name='cs_task',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talantuser',
            name='dota_task',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talantuser',
            name='steam_openid',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
