# Generated by Django 3.2.4 on 2021-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210126_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='talantuser',
            name='steam_username',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
