# Generated by Django 3.2.4 on 2021-06-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_talantuser_steam_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talantuser',
            name='blizzard_access_token',
        ),
        migrations.RemoveField(
            model_name='talantuser',
            name='blizzard_battletag',
        ),
        migrations.RemoveField(
            model_name='talantuser',
            name='blizzard_id',
        ),
        migrations.RemoveField(
            model_name='talantuser',
            name='overwatch_result',
        ),
        migrations.RemoveField(
            model_name='talantuser',
            name='overwatch_task',
        ),
        migrations.DeleteModel(
            name='OverwatchResult',
        ),
    ]
