# Generated by Django 3.2 on 2021-05-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210506_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='csresult',
            name='result_str',
            field=models.CharField(default=None, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='dotaresult',
            name='result_str',
            field=models.CharField(default=None, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='overwatchresult',
            name='result_str',
            field=models.CharField(default=None, max_length=2500, null=True),
        ),
    ]
