# Generated by Django 3.2 on 2021-05-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210508_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='csresult',
            name='error',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='csresult',
            name='result_big_str',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='csresult',
            name='result_json',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='csresult',
            name='result_num',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dotaresult',
            name='error',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dotaresult',
            name='result_big_str',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dotaresult',
            name='result_json',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='dotaresult',
            name='result_num',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='overwatchresult',
            name='error',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='overwatchresult',
            name='result_big_str',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='overwatchresult',
            name='result_json',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='overwatchresult',
            name='result_num',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='talantuser',
            name='cs_task',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talantuser',
            name='dota_task',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talantuser',
            name='overwatch_task',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
