# Generated by Django 3.2 on 2021-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210524_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='csresult',
            name='avg_cs',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='csresult',
            name='avg_give_weapon',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='csresult',
            name='avg_mvp',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='csresult',
            name='avg_plant_defuse',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='csresult',
            name='kd',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
