# Generated by Django 3.2 on 2021-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_csresult_kd'),
    ]

    operations = [
        migrations.AddField(
            model_name='csresult',
            name='kd',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
