# Generated by Django 3.2 on 2021-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_csresult_kd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csresult',
            name='kd',
        ),
        migrations.AddField(
            model_name='csresult',
            name='kd_cs',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
