# Generated by Django 3.2 on 2021-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210525_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csresult',
            name='kd_cs',
        ),
        migrations.AddField(
            model_name='csresult',
            name='kd',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
