# Generated by Django 3.2 on 2021-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210525_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csresult',
            name='kd',
            field=models.FloatField(default=None, null=True),
        ),
    ]
