# Generated by Django 3.2 on 2021-05-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_csresult_kd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csresult',
            name='kd',
            field=models.Field(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='csresult',
            name='result_json',
            field=models.JSONField(default=None, null=True),
        ),
    ]
